# -*- coding: utf-8 -*-
"""PR_iLearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LHovRgUP-93lZWu1auxy7wm5SK6BG3ep
"""

!pip install biopython
from Bio import SeqIO
import sys
import re
import os
import fileinput

import os
PATH = r"/content/drive/My Drive/prLab/dataset"

path = os.listdir(PATH)
files = [x.split('.')[0] for x in path]
print(files)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/prLab/dataset

for f in files:
    out = open(f + "_sp.txt", "w")
    mode = "train"
    classLabel = "1"

    if "test" in f:
      mode = "test"

    if f[0] == "N":
        classLabel = "0"

    for seq_record in SeqIO.parse(f + ".txt", "fasta"):
      id = str(seq_record.id) + "|" + classLabel + "|" + mode
      sequence = str(seq_record.seq)
      out.write(">" + id + "\n" + sequence + "\n")
    out.close()
    print("All good!")

#Generating KMER 1-5 for NA/PA files only.
!pwd

! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_test_sp.txt" --kmer 1 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_test_K1.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_test_sp.txt" --kmer 2 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_test_K2.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_test_sp.txt" --kmer 3 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_test_K3.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_test_sp.txt" --kmer 4 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_test_K4.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_test_sp.txt" --kmer 5 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_test_K5.csv"

! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_test_sp.txt" --kmer 1 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_test_K1.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_test_sp.txt" --kmer 2 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_test_K2.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_test_sp.txt" --kmer 3 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_test_K3.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_test_sp.txt" --kmer 4 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_test_K4.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_test_sp.txt" --kmer 5 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_test_K5.csv"

! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_train_sp.txt" --kmer 1 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_train_K1.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_train_sp.txt" --kmer 2 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_train_K2.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_train_sp.txt" --kmer 3 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_train_K3.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_train_sp.txt" --kmer 4 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_train_K4.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/NA_train_sp.txt" --kmer 5 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/NA_train_K5.csv"

! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_train_sp.txt" --kmer 1 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_train_K1.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_train_sp.txt" --kmer 2 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_train_K2.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_train_sp.txt" --kmer 3 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_train_K3.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_train_sp.txt" --kmer 4 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_train_K4.csv"
! python descnucleotide/RCKmer.py --file "/content/drive/My Drive/prLab/dataset/PA_train_sp.txt" --kmer 5 --normalize --format csv --out "/content/drive/My Drive/prLab/features/Kmer/PA_train_K5.csv"
! echo That was a lotta files

